volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
      - POSTGRES_MULTIPLE_DATABASES=radarr,lidarr,readarr,prowlarr
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - postgres/:/var/lib/postgresql/data

  arrupdate:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - Update:DataDirectory=/data
      - Update:ApiKey=
      - Update:Project=Lidarr
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    volumes:
      - ./arrupdate-data:/data
